image: mustafakhaled/android-fastlane-firebase:1.0

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  - cd ./ci
  - gem install bundler:1.17.3
  - bundle install
  - cd ..

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

  # each cached job will download and extract the cache
  # at the beginning and upload the cache at the end (временно отключено)
#cache:
#  key: ${CI_PROJECT_ID}
#  paths:
#    - .gradle/

stages:
  - test
  - deploy

test:lint:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
  tags:
    - android

test:detekt:
  stage: test
  script:
    - ./gradlew -Pci --console=plain detekt
    - ./gradlew -Pci --console=plain detektGrabSubprojectsReports
  artifacts:
    paths:
      - reports/detekt/
  tags:
    - android

test:unit:
  stage: test
  script:
    - ./gradlew -Pci --console=plain testDebugUnitTest
  tags:
    - android

deploy:debug:
  stage: deploy
  script:
    - bundle exec fastlane start_build buildType:DEBUG
  artifacts:
    expire_in: 4 hours
    paths:
      - app/build/outputs/apk/*.apk
  tags:
    - android
  only:
    - /^debug_\d{1,3}\.\d{1,3}\/\d{1,3}$/

deploy:release:
  stage: deploy
  script:
    - cd ./ci
    - bundle exec fastlane start_build buildType:RELEASE
  artifacts:
    expire_in: 4 hours
    paths:
      - app/build/outputs/apk/*.apk
  tags:
    - android
  only:
    - /^release_\d{1,3}\.\d{1,3}\/\d{1,3}$/

