image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

  # each cached job will download and extract the cache
  # at the beginning and upload the cache at the end
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
  - test
  - release
  - deploy

lintDebug:
  stage: build
  tags:
    - android
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

testDebug:
  stage: test
  tags:
    - android
  script:
    - ./gradlew -Pci --console=plain :app:testDebug

assembleDebug:
  stage: release
  tags:
    - android
  script:
    - ./gradlew assembleDebug
  artifacts:
    expire_in: 4 hours
    paths:
      - app/build/outputs/apk/app-debug.apk
