# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Define build type and assemble apk"
  lane :beta do |options|
    Dir.chdir ".." do
      if options[:build_type] == "DEBUG"
        gradle(task: "assemble", build_type: "Debug")
        distribute_firebase(firebase_group: "testers")
      elsif options[:build_type] == "RELEASE"
        gradle(task: "assemble", build_type: "Release")
        distribute_firebase(firebase_group: "mentors")
      end
    end
  end

  desc "Submit a new Build to Firebase"
  private_lane :distribute_firebase do |options|
    changelog_from_git_commits()
    # объяви app_id и firebase ci token в env.default
    # как FIREBASEAPPDISTRO_APP и FIREBASE_TOKEN
    firebase_app_distribution(
      release_notes: lane_context[SharedValues:FL_CHANGELOG],
      groups: options[:firebase_group],
    )
  end
end
